//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gadget_shop.data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Laptop
    {
        [Key]
        public int code { get; set; }
        public string model { get; set; }
        public short speed { get; set; }
        public short ram { get; set; }
        public float hd { get; set; }
        public Nullable<decimal> price { get; set; }
        public byte screen { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
