//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gadget_shop.data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Printer
    {
        [Key]
        public int code { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public string type { get; set; }
        public Nullable<decimal> price { get; set; }

        public virtual Product Product { get; set; }

        public override string ToString()
        {
            return $"Модель:{model}, колір:{color},тип:{type}";
        }
    }
}
